### ISSUE TITLE
Serial communication much slower with python 3

### ISSUE THREAD

**Issue by michaeldaas** [SiLab-Bonn/basil#103]
With python 3, a simple measurement with devices using a `Serial` TL are by a factor of 4-5 slower than with python 2.

**Comment by themperek** [comment]
Can you run profiler? 

https://github.com/rkern/line_profiler

**Comment by michaeldaas** [comment]
will do..

**Comment by DavidLP** [comment]
That would be really weird, since the slow part of serial should be the hardware interface

**Comment by DavidLP** [comment]
Is it really slower compared to Python 2 or slower compared to the code before the changes for python 3? Meaning does the code run also slower now under python 2?

**Comment by michaeldaas** [comment]
fixed in development
