### ISSUE TITLE
module with multiple classes outside of basil

### ISSUE THREAD

**Issue by thirono** [SiLab-Bonn/basil#109]
If the modules has multiple classes, it cannot be imported because of 
def _factory(self, importname, *args, **kargs) in  basil/basil/dut.py

**Comment by themperek** [comment]
example?

**Comment by thirono** [comment]
This will work:

**Comment by themperek** [comment]
Propose PR?

**Comment by thirono** [comment]
but this will not work

`hw_drivers:`
`  - name      : GPAC
`    type      : monopix_daq.customizedGPAC
`    interface : intf
`    base_addr : 0x00000
`    init :
`        no_calibration : True

**Comment by laborleben** [comment]
But now you change several parameters at once. Which item is the one you are referring to?

Be careful when changing the import function. Please check this commit https://github.com/SiLab-Bonn/basil/commit/41a2b6a68fa44850f464b18e0d30d1f5260b84e0 and the related issue: https://github.com/SiLab-Bonn/basil/issues/92

**Comment by thirono** [comment]
never mind, it was already fixed in new basil
