### ISSUE TITLE
DeprecationWarning for ABC

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/basil#110]
Warning:
```bash
/basil/RL/RegisterLayer.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```

**Comment by laborleben** [comment]
Fixed in 37a32536a8c035cc40cebb2cff31477c65a14a79.

collctions.abc will be removed in 3.10:
> Deprecated since version 3.3, will be removed in version 3.10: Moved Collections Abstract Base Classes to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.9.
