### ISSUE TITLE
SiTCP performance regression

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/basil#123]
8f712c5cf6b86f9a437ec5fbf965f7d0d4da0a8f: This commit for Python 3 compatibility reduces effective SiTCP performance from ~700Mbps to ~130Mbps (downstream TCP transfer).

**Comment by DavidLP** [comment]
Ui,  I guess it is the explicit copy to `bytearray`, that is not needed in Python 3. So we could do an explicit check for python version and use `ord` in Python 2 and nothing in Python 3.
