### ISSUE TITLE
Add markers for sbus examples

### ISSUE THREAD

**Issue by themperek** [SiLab-Bonn/basil#152]
Use pytest markers (https://docs.pytest.org/en/stable/example/markers.html) to for sbus example to be able to easily run verilator compatible tests.

**Comment by themperek** [comment]
@flooklab Could you help with this? We then have to add a test in CI for this.

**Comment by flooklab** [comment]
Only use sbus when running Verilator? i.e. remove `test_*_sbus.py`?

**Comment by themperek** [comment]
Yes. Seems enough. Will see if we can make it work in CI.
