### ISSUE TITLE
TLU working with non fei4 modules

### ISSUE THREAD

**Issue by themperek** [SiLab-Bonn/basil#18]
CMD_READY should not need to be toggled:

Suggestions:
- configuration bit

or better

- change this to trigger acknowledge signal that cmd_seq will issue (pulse at the end) for others can be tide to 1

**Comment by themperek** [comment]
Why TRIGGER_ACKNOWLEDGE == 1'b0 at https://github.com/SiLab-Bonn/basil/blob/development/device/modules/tlu/tlu_controller_fsm.v#L98 ?

Generally there is something wrong still.

**Comment by laborleben** [comment]
TLU module was updated to be more generic and simulation works now.
