### ISSUE TITLE
Mismatched function name for X-ray machine

### ISSUE THREAD

**Issue by SinuoZhang** [SiLab-Bonn/basil#185]
The two different names of the function for turning on the HV supply for X-ray tube appear in the basil HL and the example:

In the basil HL folder, where the function is defined:
https://github.com/SiLab-Bonn/basil/blob/04e3d69a51ab6388d094441ff5c0c48975649bb3/basil/HL/debyeflex3003.py#L83

In the example script, where the function is called:
https://github.com/SiLab-Bonn/basil/blob/04e3d69a51ab6388d094441ff5c0c48975649bb3/examples/lab_devices/xray_tube.py#L14

Therefore the example will not run.
Will be better to unify the name.

**Comment by MarcoVogt** [comment]
This issues is fixed.
