### ISSUE TITLE
Basil on PyPI

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/basil#38]
Since basil is not shipping scripts you need to change on a frequent basis I would recommend that we put the tags on PyPI? Its quite simple and it would ease the installation process. Unfortunately the name is already taken.

**Comment by laborleben** [comment]
name is basil_daq because wheel makes trouble

**Comment by DavidLP** [comment]
The latest tag v.2.1.2 is now on PyPI:
https://pypi.python.org/pypi/basil_daq/2.1.2

Installation is now: 

pip install basil_daq

**Comment by laborleben** [comment]
mein account ist laborleben. Bitte adde mich auch als Maintainer. Ich habe auch ein pySiLibUSB Paket erstellt.

**Comment by DavidLP** [comment]
Done
