### ISSUE TITLE
Autoupload to PyPI

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/basil#47]
Shall i add autoupload to PyPI for successfull release builds?

**Comment by laborleben** [comment]
Yes, sure. Both sdist and bdist_wheel would be great.

**Comment by DavidLP** [comment]
Mhh I think it does not work, does it?

**Comment by laborleben** [comment]
Did not last time.

**Comment by DavidLP** [comment]
True. The log on Travis is unfortunately inconclusive. We could always upload to pypitest for all development comits to check this.

**Comment by DavidLP** [comment]
I uploaded the standard package format for the 2.4.3 release. Wheel only does not seem to be sufficient, since Linux operating systems cannot use it, even if it's non binary ?!.

**Comment by laborleben** [comment]
cannot use a source package?!? That is weird...

**Comment by DavidLP** [comment]
Yes, that was not possible.

**Comment by themperek** [comment]
@DavidLP This is done?

**Comment by laborleben** [comment]
Still failing:
```
PyPI upload failed.
failed to deploy
```

**Comment by laborleben** [comment]
Maybe https://pypi.org/help/#verified-email?

**Comment by laborleben** [comment]
Fixed by commit 0b00265113cc92560f9d91a7e7cce0fe9b7dd44b.
