### ISSUE TITLE
Read during write to hardware module register

### ISSUE THREAD

**Issue by themperek** [SiLab-Bonn/basil#5]
If size and offset modulo 8 == 0 no need to read?
https://github.com/SiLab-Bonn/basil/blob/master/host/basil/HL/RegisterHardwareLayer.py#L95

**Comment by laborleben** [comment]
where is the error?

**Comment by themperek** [comment]
You do not need to read if you write full bytes. You will overwrite full byte whatever.

**Comment by laborleben** [comment]
depends on the offset and length. yes, sometimes no read is necessary. Probably it makes sense to catch this particular case.

**Comment by laborleben** [comment]
I think this makes the code to complicated to save a few bytes.

**Comment by themperek** [comment]
It is one if and for serial port communication it makes a difference.

**Comment by laborleben** [comment]
then I wold fix serial communication (whatever module), and I would not recommend using RegisterHardwareLayer. I don't see any reason to "fix" something that is working fine for 99% of the stuff.
I would use set_data() and get_data() for something that needs to be fast.

**Comment by themperek** [comment]
Serial communication (UART) uses HL drivers for modules there is no way around this.
