### ISSUE TITLE
Change firmware folder structure

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/basil#51]
The firmware folder should contain subfolders for different firmwares (FPGA modules, Arduino, etc.).

**Comment by michaeldaas** [comment]
I added an 'Arduino' subfolder in 'firmware' and moved the (so far only) Arduino firmware there. Now only the 'modules' folder needs to be renamed to something like 'FPGA modules'.

**Comment by laborleben** [comment]
See commit 22943cf60002257403852f1193390cd3fc30f076.
