### ISSUE TITLE
Configuration yaml not working

### ISSUE THREAD

**Issue by michaeldaas** [SiLab-Bonn/basil#53]
When a device is initialized like this:

```
 transfer_layer:
  - name  : device name
    type  : device type
    additional_parameter : Bar
```
Then the additional parameter(s) are not taken into account. This bug (or feature, why?) was introduced in this commit: 6f9091a

**Comment by themperek** [comment]
Full example please.

**Comment by michaeldaas** [comment]
The qMCA software as is works if i revert to an older version and does not, when i delete the three lines you deleted in the commit above...

**Comment by themperek** [comment]
Where?

**Comment by DavidLP** [comment]
Look at your commit 6f9091a. If you do not know what this did and what it does, I would recomment to revert.

**Comment by laborleben** [comment]
use
```
transfer_layer:
  - name  : device name
    type  : device type
    init:
        additional_parameter : Bar
```

**Comment by DavidLP** [comment]
I guess it has to be under init now

**Comment by michaeldaas** [comment]
It works now with the additional parameters under init, thanks.

**Comment by laborleben** [comment]
keep it as it is, and use basil as it is intended. We removed the code by intention, we kept the backward compatibility for several years. We decided to remove that.

**Comment by DavidLP** [comment]
Config file format changed. Parameter have to be under init.
