### ISSUE TITLE
CONF_DONE not working in seq_gen_core.v

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/basil#54]
Reading the state of the SEQ_GEN does not return the expected result. Simulation shows that the CONF_DONE is going high even when the SEQ_GEN is still sending out data.

**Comment by themperek** [comment]
What repeat?

**Comment by laborleben** [comment]
repeat = 1

**Comment by laborleben** [comment]
ok, this was a misunderstanding.
