### ISSUE TITLE
Remove User Layer

### ISSUE THREAD

**Issue by themperek** [SiLab-Bonn/basil#6]
Move existing UL drivers to HL and allow multiple mapping within HL.
Probably need to use something like this: http://stackoverflow.com/questions/5121931/in-python-how-can-you-load-yaml-mappings-as-ordereddicts so that initialization order is controlled.

**Comment by laborleben** [comment]
HL has to be initialized before UL, right? Can't we merge with register layer?

**Comment by themperek** [comment]
No UL is after HL. If you allow multiple assignments within HL the order of init() has to correct.
I would keep RL as is. Just remove UL.
