### ISSUE TITLE
Clean up TL base classes

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/basil#8]
Every layer needs a very simple base class.

**Comment by laborleben** [comment]
SiUart also breaks interface

**Comment by themperek** [comment]
Does not see how SiUart breaks interface (parameter names should be changed). Last time I have seen at Loe it was written better.

**Comment by laborleben** [comment]
different parameter name... exactly. Should be solved. But anyway, a general clean-up is necessary.

**Comment by laborleben** [comment]
Leo is probably still working with the SVN ... :-)

**Comment by themperek** [comment]
No. He has this concept to check in very 3 mounts.

**Comment by themperek** [comment]
Suggest change name SiSerial to Serial and SiVisa to Visa because they do not implement any protocol like SiX.
What you think?

**Comment by laborleben** [comment]
full ack

**Comment by themperek** [comment]
Should have like SiTransfareLayer as base class for SiX?
Can this API be unified? 
Any ideas? Split something?
I still like that basil give you ability to have name mapping.

**Comment by laborleben** [comment]
I recommend using abstract base class (import abc) for this kind of implementation. I can do this in the development branch.

Anyway I'm currently working on reading the calibration ROM for all types of adapter cards. The support for all adapter cards I would like to have in the new release.

**Comment by DavidLP** [comment]
I agree with the ideas, but what about renaming the TransferLayer that requires adress, data not SiTransferLayer but something that fits to its task. Since we have multiple end points a fitting word would be MultiplexingTransferLayer (http://en.wikipedia.org/wiki/Transport_layer)

**Comment by DavidLP** [comment]
And I guess it is Transport and not Transfer layer

**Comment by themperek** [comment]
It looks it is ok now?
