### ISSUE TITLE
remove host folder to make packaging/releasing simpler

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/basil#9]
do you agree?

**Comment by themperek** [comment]
I do not know but this probably make sense.

**Comment by DavidLP** [comment]
I agree.

**Comment by themperek** [comment]
Still makes sense but I would move this to future:
At the moment can be done by: 
```
pip install -e "git+https://github.com/SiLab-Bonn/basil.git#egg=basil&subdirectory=host"
```

**Comment by laborleben** [comment]
anything that prevent us to do it now?

**Comment by themperek** [comment]
This should be in principle quite safe. Can do symbolic link?
Have to updates howto in all dependencies.

What you think to upload this to pypi? It would need to by under basil-daq or something. basil is taken.

**Comment by laborleben** [comment]
the directory is not important if one uses proper imports. If someone still uses sys.path.append("/home/user/workspace/basil/host/") than it is clearly his/her fault.
